<?php

declare(strict_types=1);

namespace MiGears\Sql;

use PDO;
use Psr\Log\LoggerInterface;
use Psr\Log\NullLogger;
use MiGears\Sql\Exception\SqlException;

/**
 * INSERT query builder.
 *
 *   $id = $sql->insert('users')
 *       ->values(['name' => 'Alice', 'age' => 25])
 *       ->execute()
 *       ->lastInsertId();
 */
class SqlInsert
{
    /** @var array<string, mixed> */
    private array $values = [];

    private int $affectedRows = 0;

    /** @var string|false Id captured right after execute(); false before a successful insert */
    private string|false $lastInsertId = false;

    public function __construct(
        private readonly PDO $pdo,
        private readonly string $table,
        private readonly LoggerInterface $logger = new NullLogger(),
    ) {
    }

    /**
     * Sets the insert data (key-value array).
     *
     * @param array<string, mixed> $data
     */
    public function values(array $data): self
    {
        $this->values = $data;
        return $this;
    }

    /**
     * Generates the INSERT SQL string.
     */
    public function toSql(): string
    {
        if ($this->values === []) {
            throw new SqlException('Insert values must be provided via values()');
        }

        $columns = array_keys($this->values);
        foreach ($columns as $column) {
            $this->assertValidColumn((string) $column);
        }
        $cols = '`' . implode('`, `', $columns) . '`';
        $placeholders = ':' . implode(', :', $columns);

        return "INSERT INTO `{$this->table}` ({$cols}) VALUES ({$placeholders})";
    }

    /**
     * Executes the INSERT, returns self for chained lastInsertId() / rowCount() calls.
     */
    public function execute(): self
    {
        $sql = $this->toSql();
        $this->logger->debug('SQL: {sql}', ['sql' => $sql, 'params' => $this->values]);

        $stmt = $this->pdo->prepare($sql);
        if ($stmt === false) {
            throw new SqlException("Failed to prepare statement: {$sql}");
        }
        foreach ($this->values as $key => $value) {
            $stmt->bindValue($key, $value);
        }
        if (!$stmt->execute()) {
            throw new SqlException("Failed to execute statement: {$sql}");
        }

        $this->affectedRows = $stmt->rowCount();
        $this->lastInsertId = $this->pdo->lastInsertId();
        return $this;
    }

    /**
     * Returns the number of affected rows.
     */
    public function rowCount(): int
    {
        return $this->affectedRows;
    }

    /**
     * Returns the id generated by this insert.
     *
     * The value is captured immediately after execute(), so a later statement
     * on the same connection cannot change it. PDO exposes the id per
     * connection, so concurrent inserts on one connection are still not
     * distinguishable from each other.
     */
    public function lastInsertId(): string|false
    {
        return $this->lastInsertId;
    }

    /**
     * Rejects column names that could break out of the backtick-quoted
     * identifier (e.g. "name` , email = 'x' -- ").
     */
    private function assertValidColumn(string $column): void
    {
        if (!preg_match('/^\w+$/', $column)) {
            throw new SqlException("Invalid column name: {$column}");
        }
    }
}
